apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-schema-migration
  namespace: apps
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ghcr.io/tibia-oce/migrate:0.1.0
          env:
            # Static variables
            - name: MARIADB_PORT
              value: "3306"
            - name: MARIADB_HOST
              value: "mariadb.apps.svc.cluster.local"
            # External secrets
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: myaac-mariadb-database
            - name: MARIADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-user
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-root-password
