apiVersion: apps/v1
kind: Deployment
metadata:
  name: tibia
  namespace: apps
  labels:
    app: tibia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tibia
  template:
    metadata:
      labels:
        app: tibia
    spec:
      containers:
        - name: tibia
          image: ghcr.io/tibia-oce/server:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:

            # Static variables
            - name: LOGIN_PROTOCOL_PORT
              value: "7171"
            - name: GAME_PROTOCOL_PORT
              value: "7172"
            - name: STATUS_PROTOCOL_PORT
              value: "7171"  # 7172?

            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: "mariadb.apps.svc.cluster.local"
            - name: MYSQL_SOCK
              value: "/opt/bitnami/mariadb/tmp/mysql.sock"
            - name: MYSQL_DATABASE
              value: "forgottenserver"
            - name: MYSQL_USER
              value: "root"
            - name: SERVER_IP
              value: "159.13.41.229" # "game.mythbound.dev" "192.9.185.149"

            # External secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tibia
                  key: tibia-mariadb-root-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tibia
                  key: tibia-mariadb-root-password
