extra_server_args: ""

k3s_kubectl_binary: k3s kubectl

group_name_master: master

retry_count: 20

# yamllint disable rule:line-length
server_init_args: >-
  {% if groups[group_name_master | default('master')] | length > 1 %}
    {% if ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] %}
      --cluster-init
    {% else %}
      --server https://{{ hostvars[groups[group_name_master | default('master')][0]].k3s_node_ip | split(",") | first | ansible.utils.ipwrap }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %} {{ extra_server_args }}

systemd_dir: /etc/systemd/system
